Specify descendants lookup for `CostQuery::Filter::{filters}`
As we have introduced a `Comments` module, when using const_get/const_defined? without specifying inherit = false,
then lookup will happen on ancestors as well which would resolve incorrectly to the `Comments` module, leading to a NameError

```ruby
NoMethodError:
       undefined method 'label' for module Comments
     # ./modules/reporting/app/helpers/reporting_helper.rb:59:in 'ReportingHelper#label_for'
```